### ISSUE TITLE
GPG issue during/after install

### ISSUE THREAD

**Issue by DevonianTeuchter** [DevonianTeuchter/meta#15]
zopen install gpg results in message:
<snip>
mkdir: FSUM6404 directory "/u/jenkins/.gnupg": EDC5129I No such file or directory.
./setup.sh 47: FSUM7343 cannot open "/u/jenkins/.gnupg/gpg-agent.conf" for output: EDC5129I No such file or directory.

See upstream package issue: 
https://github.com/ZOSOpenTools/gpgport/issues/6

**Comment by DevonianTeuchter** [comment]
Expanding on the comments in the issue linked above:
After install  (zopen install gpg) , create a gpg-agent.conf file in your $HOME/.gnupg directory

_pinentry-program $ZOPEN_ROOTFS/usr/bin/pinentry-tty_
log-file _/<your home dir>/.gnupg/gpg-agent.log_  or  _$ZOPEN_ROOTFS/var/log/gpg-agent.log_  possibly

gpg-agent can be restarted within a zopen env (using commands such as:
::>_gpg-connect-agent --agent-program `which gpg-agent` reloadagent_

**Comment by HarithaIBM** [comment]
Tried `zopen install gpg` and also `zopen upgrade gpg`. it worked fine
