### ISSUE TITLE
Project specific environment variables

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [DevonianTeuchter/meta#21]
Is the .zopen-config able to pick up project specific environment variables?

For example, vim has the `VIM` environment variable to specify it's runtime, which is currently set in the project's .env file.

**Comment by IgorTodorovskiIBM** [comment]
.zopen-config should project specific env files in etc/profiled/, which should source the .env

Igor to test it out

**Comment by DevonianTeuchter** [comment]
As discussed, ports/packages that have a .env will have that file sourced during initialisation of the zopen system, sourced from within the project's install location so custom envvars *should* be configured as expected. Awaiting f/b...

**Comment by HarithaIBM** [comment]
I have tested vim , man-db and git. There were no issues. Hence closing it.
