### ISSUE TITLE
zopen remove is not removing all related binaries 

### ISSUE THREAD

**Issue by HarithaIBM** [DevonianTeuchter/meta#53]
When i tried `zopen remove gpg` i observed that only gpg removed but other binaries like dirmngr, gpg-connect-agent and many more which were installed as part of command `zopen install gpg` are not removed

**Comment by DevonianTeuchter** [comment]
The root issue is that although the package is called gpg to install, it actually installs to gnupg so the removal matching logic fails...

**Comment by HarithaIBM** [comment]
Yes right, we might need logic to keep track of binaries and config files created as part of installation process, (meta data). to be used during uninstall?

**Comment by DevonianTeuchter** [comment]
Actually... digging further, that's a red herring ;-)  The root cause is the logic added to try and speed up removal by multi-processing - it should affect other ports as well.

**Comment by IgorTodorovskiIBM** [comment]
What is being used for multi-processing currently? Should we port GNU Parallel or [rush](https://github.com/shenwei356/rush)?

**Comment by DevonianTeuchter** [comment]
Custom code ;-)  We could port parallel/rush though that is then another package to ship [not a deal-breaker, just a consideration]
